### ISSUE TITLE
Feature: Output Images in vector format for mebs_output.py and F_MEBS_cluster.py

### ISSUE THREAD

**Issue by bstamps** [eead-csic-compbio/metagenome_Pfam_score#4]
Would it be possible to modify the visual output scripts to either allow for file format selection, or by default output to PDF or SVG rather than PNG to allow the figures to be edited/scaled/etc.?

**Comment by valdeanda** [comment]
Hi Blake
Sure, thank for the suggestion
We are going to  implementon the option to select different types of
outputs :PDF, jpg, ps, eps ,  svg and PNG
We will let you know when is ready
Best
Valerie, Cesar and Bruno

**Comment by acpooth** [comment]
Hi,

The requested feature was added. Now you can specify the image output format  with the option -f. 

Example:
- For svg format
`python3 mebs_output.py test.genomes.tsv  -f svg  `

See scripts help text ( option -h) for more information.

Best regards

**Comment by bstamps** [comment]
Works wonderfully. Thank you for closing out this issue so quickly!
